# 1) Сначала построим Matrix A и column f

In [1]:
from math import sqrt
import numpy as np

a = [1,5,1]*48
b = [5,1] + [0]*48
c = [[0]*(x/3) + a[x:x+3] + [0]*(47 - x/3) for x in xrange(0, 48*3, 3)]
d = [1]*50
A = np.vstack([b, c,d])
#A

In [3]:
f = range(1, 51)

# 2) Вот как они выглядят

In [4]:
print A, '\n\n', f, '\n'

[[5 1 0 ... 0 0 0]
 [1 5 1 ... 0 0 0]
 [0 1 5 ... 0 0 0]
 ...
 [0 0 0 ... 5 1 0]
 [0 0 0 ... 1 5 1]
 [1 1 1 ... 1 1 1]] 

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50] 



# 3)Метод Зейделя

In [28]:
def seidel(A, b, eps):
    
    n = len(A)
    x = [.0 for i in range(n)]

    converge = False
    
    while not converge:
        x_new = np.copy(x)
        for i in range(n):
            s1 = sum(A[i][j] * x_new[j] for j in range(i))
            s2 = sum(A[i][j] * x[j] for j in range(i + 1, n))
            x_new[i] = (b[i] - s1 - s2) / A[i][i]
#Критерий останова!!!
        converge = sqrt(sum((x_new[i] - x[i]) ** 2 for i in range(n))) <= eps
# Вычисление и печать невязки
        residue = b - np.dot(A, x_new)
        print 'The norm of the residue(third norm):'
        print np.linalg.norm(residue, ord=3)
        
        x = x_new

    return x

# 4) Метод Гаусса

## Данная функция не работает для решения произвольных систем методом гаусса, т.к. здесь реализован выбор первого элемента в столбце, а не наибольшего по модулю

In [29]:
def gauss(A, b):
    n = len(A)
    A = np.array(A)
    A = A.astype(float)
    
    
    A = np.column_stack((A, b))
    
    for j in range(0, n):
        for i in range(j+1,n):
            if A[i][j] != 0:
                A[i] = A[i] - A[i][j]/A[j][j] * A[j]
                       
    x = np.array([.0 for i in range(n)])
    
    for i in range(n-1, -1, -1):
        x[i] = A[i][n]/A[i][i] - sum(A[i][k]/A[i][i]*x[k] for k in range(i+1, n))
    return x

# 5) Теперь посчитаем результат для двух методов и сравним его с тем что должно было получиться

In [30]:
x = seidel(A, f, 10**-3)
print '\nresult is'
print x
print '\nerf is:'
print x - np.linalg.solve(A,f)

The norm of the residue(third norm):
155.6293744226537
The norm of the residue(third norm):
31.401518443688527
The norm of the residue(third norm):
6.325537414841872
The norm of the residue(third norm):
1.283985028542123
The norm of the residue(third norm):
0.26642503432827086
The norm of the residue(third norm):
0.057085404149876055
The norm of the residue(third norm):
0.012650187445103392
The norm of the residue(third norm):
0.0028829778857805658
The norm of the residue(third norm):
0.000670382052818896

result is
[ 1.42857331e-01  2.85714459e-01  4.28571621e-01  5.71428777e-01
  7.14285934e-01  8.57143091e-01  1.00000025e+00  1.14285741e+00
  1.28571456e+00  1.42857172e+00  1.57142888e+00  1.71428603e+00
  1.85714319e+00  2.00000035e+00  2.14285750e+00  2.28571466e+00
  2.42857182e+00  2.57142898e+00  2.71428613e+00  2.85714329e+00
  3.00000045e+00  3.14285760e+00  3.28571476e+00  3.42857192e+00
  3.57142907e+00  3.71428623e+00  3.85714339e+00  4.00000055e+00
  4.14285770e+00  4.285

In [32]:
x = gauss(A, f)
print '\nresult is'
print x
print '\nerf is:'
print x - np.linalg.solve(A,f)


result is
[ 1.42857143e-01  2.85714286e-01  4.28571429e-01  5.71428571e-01
  7.14285714e-01  8.57142857e-01  1.00000000e+00  1.14285714e+00
  1.28571429e+00  1.42857143e+00  1.57142857e+00  1.71428571e+00
  1.85714286e+00  2.00000000e+00  2.14285714e+00  2.28571429e+00
  2.42857143e+00  2.57142857e+00  2.71428571e+00  2.85714286e+00
  3.00000000e+00  3.14285714e+00  3.28571429e+00  3.42857143e+00
  3.57142857e+00  3.71428571e+00  3.85714286e+00  4.00000000e+00
  4.14285714e+00  4.28571429e+00  4.42857143e+00  4.57142857e+00
  4.71428571e+00  4.85714286e+00  5.00000001e+00  5.14285710e+00
  5.28571451e+00  5.42857034e+00  5.57143380e+00  5.71426066e+00
  5.85726289e+00  5.99942489e+00  6.14561264e+00  6.27251188e+00
  6.49182794e+00  6.26834840e+00  8.16643008e+00 -1.00498772e-01
  4.03360638e+01 -1.52579820e+02]

erf is:
[ 2.77555756e-17 -5.55111512e-17 -5.55111512e-17  0.00000000e+00
  0.00000000e+00 -1.11022302e-16  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00 -2.

## Видно, что даже метод гаусса(прямой метод) не дает точного решения данной системы из-за неточного представления числа в памяти компьютера

# 6) Найдем наибольшие и наименьшие собственные числа матрицы, определим число обусловленности

In [33]:
n, v = np.linalg.eig(A)
print 'All eigenvalues'
print n

print 'Max eigenvalue:'
print max(n)
print 'Min eigenvalue:'
print min(n)

print 'The condition number of a matrix(frobenius norm):'
print np.linalg.cond(A, p = 'fro')
print 'The condition number of a matrix(first norm):'
print np.linalg.cond(A, p = 1)
print 'The condition number of a matrix(second norm):'
print np.linalg.cond(A, p = 2)


All eigenvalues
[0.79793197 3.00397825 3.0157706  3.03570655 3.06283368 3.09864451
 3.14044703 3.1917674  3.24738664 3.3135675  3.38196601 3.46208508
 3.54206275 3.63494485 3.72515202 3.82939648 3.92834641 4.04235868
 4.14844142 4.27046687 4.38196601 4.51012456 4.62523737 4.75755805
 4.87441896 5.00887424 5.12558104 5.26012047 5.37476263 5.50734577
 5.61803399 5.74666227 7.02359238 6.9842294  6.97523991 6.93716632
 6.91370837 6.85955297 6.82142343 6.75261336 6.70039037 6.61803399
 6.55262501 5.85155858 6.45793725 6.38048615 6.27484798 6.186695
 5.97430589 6.07165359]
Max eigenvalue:
7.02359237578879
Min eigenvalue:
0.7979319694208489
The condition number of a matrix(frobenius norm):
87.85592866972526
The condition number of a matrix(first norm):
12.220201853215574
The condition number of a matrix(second norm):
17.46494635321572


## Видно, что в зависимости от определения нормы мы получаем различные числа обусловленности для матрицы

# 7)Давайте теперь проверим скорость исполнения методов расчета системы

In [34]:
%timeit gauss(A, f)
%timeit seidel(A, f, 10**-3)
#timeit производит несколько запусков и вычисляет среднее время работы

1000 loops, best of 3: 1.4 ms per loop
The norm of the residue(third norm):
155.6293744226537
The norm of the residue(third norm):
31.401518443688527
The norm of the residue(third norm):
6.325537414841872
The norm of the residue(third norm):
1.283985028542123
The norm of the residue(third norm):
0.26642503432827086
The norm of the residue(third norm):
0.057085404149876055
The norm of the residue(third norm):
0.012650187445103392
The norm of the residue(third norm):
0.0028829778857805658
The norm of the residue(third norm):
0.000670382052818896
The norm of the residue(third norm):
155.6293744226537
The norm of the residue(third norm):
31.401518443688527
The norm of the residue(third norm):
6.325537414841872
The norm of the residue(third norm):
1.283985028542123
The norm of the residue(third norm):
0.26642503432827086
The norm of the residue(third norm):
0.057085404149876055
The norm of the residue(third norm):
0.012650187445103392
The norm of the residue(third norm):
0.00288297788578056

The norm of the residue(third norm):
0.0028829778857805658
The norm of the residue(third norm):
0.000670382052818896
The norm of the residue(third norm):
155.6293744226537
The norm of the residue(third norm):
31.401518443688527
The norm of the residue(third norm):
6.325537414841872
The norm of the residue(third norm):
1.283985028542123
The norm of the residue(third norm):
0.26642503432827086
The norm of the residue(third norm):
0.057085404149876055
The norm of the residue(third norm):
0.012650187445103392
The norm of the residue(third norm):
0.0028829778857805658
The norm of the residue(third norm):
0.000670382052818896
The norm of the residue(third norm):
155.6293744226537
The norm of the residue(third norm):
31.401518443688527
The norm of the residue(third norm):
6.325537414841872
The norm of the residue(third norm):
1.283985028542123
The norm of the residue(third norm):
0.26642503432827086
The norm of the residue(third norm):
0.057085404149876055
The norm of the residue(third norm):

The norm of the residue(third norm):
0.000670382052818896
The norm of the residue(third norm):
155.6293744226537
The norm of the residue(third norm):
31.401518443688527
The norm of the residue(third norm):
6.325537414841872
The norm of the residue(third norm):
1.283985028542123
The norm of the residue(third norm):
0.26642503432827086
The norm of the residue(third norm):
0.057085404149876055
The norm of the residue(third norm):
0.012650187445103392
The norm of the residue(third norm):
0.0028829778857805658
The norm of the residue(third norm):
0.000670382052818896
The norm of the residue(third norm):
155.6293744226537
The norm of the residue(third norm):
31.401518443688527
The norm of the residue(third norm):
6.325537414841872
The norm of the residue(third norm):
1.283985028542123
The norm of the residue(third norm):
0.26642503432827086
The norm of the residue(third norm):
0.057085404149876055
The norm of the residue(third norm):
0.012650187445103392
The norm of the residue(third norm):


## При таком расчете метод гаусса дает 1,4 мс, а метод Зейделя 51.9 мс. Теперь выберем меньшую погрешность и сравним результаты.

In [48]:
%%time
x = gauss(A, f)
print x - np.linalg.solve(A,f)

[ 2.77555756e-17 -5.55111512e-17 -5.55111512e-17  0.00000000e+00
  0.00000000e+00 -1.11022302e-16  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00 -2.22044605e-16  0.00000000e+00
 -2.22044605e-16  0.00000000e+00 -4.44089210e-16  0.00000000e+00
  4.44089210e-16  0.00000000e+00  4.44089210e-16  0.00000000e+00
 -4.44089210e-16 -4.44089210e-16 -4.44089210e-16  4.44089210e-16
 -4.44089210e-16  4.44089210e-16  8.88178420e-16  0.00000000e+00
  0.00000000e+00  8.88178420e-16 -8.88178420e-16 -8.88178420e-16
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00 -8.88178420e-16  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
 -8.88178420e-16  8.88178420e-16 -1.77635684e-15  2.34534614e-15
 -7.10542736e-15  0.00000000e+00]
CPU times: user 5.44 ms, sys: 57 µs, total: 5.5 ms
Wall time: 4.55 ms


In [51]:
%%time
x = seidel(A, f, 10**-7)
print x - np.linalg.solve(A,f)

The norm of the residue(third norm):
155.6293744226537
The norm of the residue(third norm):
31.401518443688527
The norm of the residue(third norm):
6.325537414841872
The norm of the residue(third norm):
1.283985028542123
The norm of the residue(third norm):
0.26642503432827086
The norm of the residue(third norm):
0.057085404149876055
The norm of the residue(third norm):
0.012650187445103392
The norm of the residue(third norm):
0.0028829778857805658
The norm of the residue(third norm):
0.000670382052818896
The norm of the residue(third norm):
0.00015801336279888775
The norm of the residue(third norm):
3.7589574512977734e-05
The norm of the residue(third norm):
9.000999867582166e-06
The norm of the residue(third norm):
2.1659950458933697e-06
The norm of the residue(third norm):
5.232516215538841e-07
The norm of the residue(third norm):
1.2680430565767658e-07
The norm of the residue(third norm):
3.081032157099129e-08
[-1.15482623e-12 -1.01985087e-12 -1.10167431e-12 -1.14708243e-12
 -1.198

## При таком расчете метод гаусса дает 5 мс, а метод Зейделя 110 мс. Результат медленнее для Зейделя, но зато стал гораздо точнее